apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "metadata-injector.fullname" . }}
webhooks:
  - name: "kubernetes-metadata-injector.kubernetes.io"
    matchPolicy: Equivalent
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["services"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "metadata-injector.fullname" . }}
        path: /mutate-svc
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    {{- if .Values.admissionWebhookConfig.timeoutSeconds }}
    timeoutSeconds: {{ .Values.admissionWebhookConfig.timeoutSeconds }}
    {{- end }}
    {{- if .Values.admissionWebhookConfig.namespaceSelector }}
    namespaceSelector: {{ toYaml .Values.admissionWebhookConfig.namespaceSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.admissionWebhookConfig.objectSelector }}
    objectSelector: {{ toYaml .Values.admissionWebhookConfig.objectSelector | nindent 6 }}
    {{- end }}
