apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "metadata-injector.fullname" . }}-create-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
    {{- with .Values.patch.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
{{- end }}
  template:
    metadata:
      name: {{ include "metadata-injector.fullname" . }}-create-secret-job
    {{- if .Values.patch.podAnnotations }}
      annotations: {{ toYaml .Values.patch.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "metadata-injector.labels" . | nindent 8 }}
        {{- with .Values.patch.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      containers:
        - name: create
          {{- with .Values.patch.image }}
          image: {{ if .repository }}{{ .repository }}{{ else }}{{ .registry }}/{{ .image }}{{ end }}:{{ .tag }}{{ if .digest }}@{{ .digest }}{{ end }}
          {{- end }}
          imagePullPolicy: {{ .Values.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ include "metadata-injector.fullname" . }},{{ include "metadata-injector.fullname" . }}.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name={{ include "metadata-injector.fullname" . }}-tls
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.patch.createSecretJob.securityContext }}
          securityContext: {{ toYaml .Values.patch.createSecretJob.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.patch.createSecretJob.resources }}
          resources: {{ toYaml .Values.patch.createSecretJob.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "metadata-injector.serviceAccountName" . }}-patch
    {{- if .Values.patch.nodeSelector }}
      nodeSelector: {{ toYaml .Values.patch.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.patch.tolerations }}
      tolerations: {{ toYaml .Values.patch.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.patch.securityContext }}
      securityContext: {{ toYaml .Values.patch.securityContext | nindent 8 }}
    {{- end }}