apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata-injector.serviceAccountName" . }}-patch
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
    {{- with .Values.patch.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
