apiVersion: v1
kind: Service
metadata:
  name: ignored
  namespace: apps
  annotations:
    ignored-annotation: igonred
    moveax.injector.service.aaa: igonred
spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: ignored
    app.kubernetes.io/name: ignored