apiVersion: v1
kind: Service
metadata:
  name: injectable
  namespace: apps
  annotations:
    ignored-annotation: igonred
    moveax.injector.annotation.custom-annotation/subpath: "apps/source-configmap:inject"
spec:
  spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: injectable
    app.kubernetes.io/name: injectable