apiVersion: v1
kind: Service
metadata:
  name: malformed
  namespace: apps
  annotations:
    moveax.injector.annotation.custom-annotation/subpath: "default/source-configmap"
spec:
  spec:
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: malformed
    app.kubernetes.io/name: malformed