apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubernetes-metadata-injector
  name: kubernetes-metadata-injector
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kubernetes-metadata-injector
  name: kubernetes-metadata-injector
rules:
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, watch]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [list, get, watch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kubernetes-metadata-injector
  name: kubernetes-metadata-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-metadata-injector
subjects:
  - kind: ServiceAccount
    name: kubernetes-metadata-injector
    namespace: default