apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata-injector.fullname" . }}
  labels:
    {{- include "metadata-injector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "metadata-injector.selectorLabels" . | nindent 4 }}
